syntax on
filetype plugin indent on
set et ts=4 sw=4 nu hlsearch ruler ignorecase smartcase nomodeline bg=dark incsearch
set path=**/* grepprg=rg\ --vimgrep grepformat^=%f:%l:%c:%m backspace=2 nojs
nnoremap <Leader>\ gqj
command OLD :enew | setl buftype=nofile | 0put =v:oldfiles | nnoremap <buffer> <CR> :e <C-r>=getline('.')<CR><CR>

let g:gutentags_enabled = 0
let g:gutentags_generate_on_new = 0
let g:gutentags_cache_dir = '~/.vim/ctags'
let b:gutentags_file_list_command = 'git ls-files'

" bits from vim-sensible
set autoindent smarttab nrformats-=octal
nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
set laststatus=2 wildmenu scrolloff=1 sidescrolloff=5 display+=lastline encoding=utf-8
set formatoptions+=j history=1000 tabpagemax=50 sessionoptions-=options

" so Gdiff and vimdiff output are somewhat readable
if &diff
    syntax off
endif

if has("patch-8.1-0360")
  set diffopt+=algorithm:patience
endif

" html
au FileType html setlocal ts=2 sw=2 sws=2

" ruby
au BufRead,BufNewFile Vagrantfile setfiletype ruby

" starlark
au BufRead,BufNewFile *.star setfiletype python

" puppet
au BufRead,BufNewFile *.pp setfiletype puppet
au FileType puppet setlocal ts=2 sw=2 sws=2 syntax=ruby
au FileType puppet let g:gutentags_enabled = 1
au FileType puppet let b:gutentags_file_list_command = 'git ls-files *.pp'
au FileType puppet nnoremap <buffer> <C-]> :call search('\s', 'b')<cr>:call search('\w')<cr>vE<C-]>
"au FileType puppet nnoremap <buffer> <C-]> :call search('\s', 'b')<cr>:call search('\w')<cr>:call search('[^a-z:]\|$', 's')<cr>hv`'<C-]>

" avro
au BufRead,BufNewFile *.avsc setfiletype json
au BufRead,BufNewFile *.avsc setlocal ts=2 sw=2 sws=2

" go
au FileType go setlocal noet
au FileType go nnoremap <buffer> <C-]> :GoDef<CR>
au FileType go let g:go_template_autocreate = 0
au FileType go let g:go_fmt_command = "goimports"
let g:go_fmt_command = "goimports"
let g:go_fmt_options = {
    \ 'goimports': '-local selector,inventory,gopkg.in,google.golang.org,code.uber.internal,thriftrw,thrift,gogoproto,go.uber.org,golang.org,github.com,mock',
    \ }
let $USEGO111MODULE="off"

" strace
au FileType strace set nonu

" yaml
au FileType yaml set ts=2 sw=2

" sql
au FileType sql setlocal formatprg=pg_format\ -

" mail
autocmd BufRead,BufNewFile *mutt-* setfiletype mail
