syntax on
filetype plugin indent on
set et ts=4 sw=4 nu hlsearch ruler ignorecase smartcase nomodeline bg=dark incsearch
set path=**/* grepprg=rg\ --vimgrep grepformat^=%f:%l:%c:%m

if has("patch-8.1-0360")
  set diffopt+=algorithm:patience
endif

" inspired by vim-sensible
set autoindent smarttab nrformats-=octal
" Use <C-L> to clear the highlighting of :set hlsearch.
nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
set laststatus=2 wildmenu scrolloff=1 sidescrolloff=5 display+=lastline encoding=utf-8
set formatoptions+=j history=1000 tabpagemax=50 sessionoptions-=options

let g:gutentags_enabled = 0
let g:gutentags_generate_on_new = 0
let g:gutentags_cache_dir = '/Users/motiejus/.vim/ctags'
let b:gutentags_file_list_command = 'git ls-files'

let g:ale_fix_on_save = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
let g:ale_set_highlights = 0
let g:ale_set_signs = 0

" html
au FileType html setlocal ts=2 sw=2 sws=2

" ruby
au BufRead,BufNewFile Vagrantfile setfiletype ruby

" buck
au BufRead,BufNewFile BUCK setfiletype python

" puppet
au BufRead,BufNewFile *.pp setfiletype puppet
au FileType puppet setlocal ts=2 sw=2 sws=2 syntax=ruby
au FileType puppet let g:gutentags_enabled = 1
au FileType puppet let b:gutentags_file_list_command = 'git ls-files *.pp'
au FileType puppet nnoremap <C-]> :call search('\s', 'b')<cr>:call search('\w')<cr>vE<C-]>
"au FileType puppet nnoremap <C-]> :call search('\s', 'b')<cr>:call search('\w')<cr>:call search('[^a-z:]\|$', 's')<cr>hv`'<C-]>

" avro
au BufRead,BufNewFile *.avsc setfiletype json
au BufRead,BufNewFile *.avsc setlocal ts=2 sw=2 sws=2

" go
au FileType go setlocal noet
au FileType go let b:ale_linters = ['golangci-lint', 'gopls']
au FileType go let b:ale_fixers = ['goimports']
au FileType go nnoremap <C-]> :ALEGoToDefinition<CR>

" rust
au FileType rust let g:rustfmt_autosave = 1
au FileType rust setlocal tags=./rusty-tags.vi;/,$RUST_SRC_PATH/rusty-tags.vi
au BufWritePost *.rs :silent! exec "!rusty-tags vi --quiet --start-dir=" . expand('%:p:h') . "&" | redraw!

" sql
let g:omni_sql_no_default_maps = 1
