#!/bin/bash

declare -x DISPLAY=":0.0"
declare -x XAUTHORITY="/home/motiejus/.Xauthority"

case $1/$2 in
    post/*)
        sleep 5
        synclient TapButton3=2 HorizTwoFingerScroll=1
        ;;
esac
