#!/bin/bash

# Original script was using /bin/sh but shellcheck reporting warnings.

# NAME: custom-xhci_hcd
# PATH: /lib/systemd/system-sleep
# CALL: Called from SystemD automatically
# DESC: Suspend broken for USB3.0 as of Oct 25/2018 various kernels all at once

# DATE: Oct 28 2018.

# NOTE: From comment #61 at: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/522998

TMPLIST=/tmp/xhci-dev-list

# Original script was: case "${1}" in hibernate|suspend)

case $1/$2 in
    pre/*)
        echo "$0: Going to $2..."
        echo -n '' > $TMPLIST
        for i in `ls /sys/bus/pci/drivers/xhci_hcd/ | egrep '[0-9a-z]+\:[0-9a-z]+\:.*$'`; do
            # Unbind xhci_hcd for first device XXXX:XX:XX.X:
            echo -n "$i" | tee /sys/bus/pci/drivers/xhci_hcd/unbind
            echo "$i" >> $TMPLIST
        done
        ;;
    post/*)
        echo "$0: Waking up from $2..."
        for i in `cat $TMPLIST`; do
            # Bind xhci_hcd for first device XXXX:XX:XX.X:
            echo -n "$i" | tee /sys/bus/pci/drivers/xhci_hcd/bind
        done
        rm $TMPLIST
        ;;
esac
